# Generated by Django 4.2.27 on 2026-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebTeammember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('food_preference', models.CharField(max_length=255)),
                ('tshirt_size', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'web_teammember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('team_leader_name', models.CharField(max_length=255)),
                ('team_leader_email', models.CharField(max_length=255)),
                ('team_leader_mobile', models.CharField(max_length=255)),
                ('team_size', models.IntegerField()),
                ('college_selection', models.CharField(max_length=255)),
                ('college_name_other', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_screenshot', models.CharField(blank=True, max_length=255, null=True)),
                ('project_document', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Web Registration',
                'verbose_name_plural': 'Web Registrations',
                'db_table': 'web_registration',
                'managed': True,
            },
        ),
    ]
