# Generated by Django 4.2.27 on 2026-01-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_fixed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webregistration',
            name='idea_theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webregistration',
            name='selection_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
