# Generated by Django 4.2.27 on 2026-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_fixed', '0002_webregistration_idea_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webregistration',
            name='project_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
