# Generated by Django 4.2.7 on 2026-01-29 17:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=255, unique=True)),
                ("team_leader_name", models.CharField(max_length=255)),
                ("team_leader_email", models.EmailField(max_length=254)),
                ("team_leader_mobile", models.CharField(max_length=15)),
                (
                    "team_size",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                (
                    "college_selection",
                    models.CharField(
                        choices=[
                            ("NRCM", "Narsimha Reddy Engineering College"),
                            ("OTHER", "Other"),
                        ],
                        default="NRCM",
                        max_length=10,
                    ),
                ),
                (
                    "college_name_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if college is not NRCM",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(help_text="UTR ID", max_length=100, unique=True),
                ),
                (
                    "payment_screenshot",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "project_document",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="raw"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("roll_no", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="web.registration",
                    ),
                ),
            ],
        ),
    ]
