# Generated by Django 4.2.7 on 2026-01-29 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="team_leader_mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be 10 digits starting with 6-9",
                        regex="^[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="team_size",
            field=models.IntegerField(
                choices=[(2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
