# Generated by Django 4.2.27 on 2026-01-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_registration_team_leader_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='food_preference',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10),
        ),
        migrations.AddField(
            model_name='teammember',
            name='tshirt_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=10),
        ),
    ]
