# Generated by Django 4.2.27 on 2026-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_teammember_food_preference_teammember_tshirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='food_preference',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON-VEG', 'Non-Vegetarian')], default='VEG', max_length=10),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='tshirt_size',
            field=models.CharField(choices=[('S', 'Small (S)'), ('M', 'Medium (M)'), ('L', 'Large (L)'), ('XL', 'Extra Large (XL)'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=5),
        ),
    ]
