# Generated by Django 4.2.27 on 2026-01-30 08:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_teammember_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UTR ID', max_length=100, null=True, unique=True),
        ),
    ]
