# Generated by Django 4.2.27 on 2026-01-30 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_registration_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='mobile',
            field=models.CharField(default='9999999999', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits starting with 6-9', regex='^[6-9]\\d{9}$')]),
        ),
    ]
