# Generated by Django 4.2.27 on 2026-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_teammember_email_teammember_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='project_category',
            field=models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering'), ('CSE', 'Computer Science and Engineering & Emerging Areas'), ('ECE', 'Electronics and Communication Engineering'), ('MBA', 'Master of Business Administration'), ('IT', 'Information Technology'), ('MCA', 'Master of Computer Applications'), ('SH', 'Science & Humanities'), ('EEE', 'Electrical & Electronics Engineering')], default='CSE', max_length=50),
        ),
    ]
