# Generated by Django 4.2.27 on 2026-02-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_registration_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='selection_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
